name: greenleaf
description: A GreenLeaf recycling app.
publish_to: 'none' 
version: 1.0.0+1

  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1
  mobile_scanner: ^3.0.0-dev.1 # Versão mais recente
  syncfusion_flutter_datepicker: ^21.1.40
  intl: ^0.18.1
  #firebase_core: ^2.4.1
  #firebase_auth: ^4.2.5
  #cloud_firestore: ^4.3.1
  #firebase_storage: ^11.0.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
